# =========================
# Application
# =========================
spring.application.name=supplysync-backend

# =========================
# Database
# =========================
spring.datasource.url=jdbc:mysql://localhost:3306/supplysync
spring.datasource.username=root
spring.datasource.password=Harsh@9198

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Server
# =========================
server.port=8081

# =========================
# JWT
# =========================
jwt.secret=supplysync_dev_secret_key_change_this_later_1234567890
jwt.expiration=86400000

# =========================
# Swagger
# =========================
springdoc.swagger-ui.path=/swagger-ui.html